### ISSUE TITLE
2.0 branch

### ISSUE THREAD

**Issue by haefeli** [dreamfactorysoftware/openshift-dreamfactory-cartridge#1]
Will there be a 2.0 branch released for this? Let me know if/how I can contribute. Thanks.

**Comment by todda48** [comment]
This is in progress. Thanks for the offer to help.

**Comment by todda48** [comment]
2.0 version is available now.

**Comment by df-jablan** [comment]
@haefeli Please create a feature branch (based off of our develop branch) in your fork, and issue a pull request when ready. Thanks! :+1:
