### ISSUE TITLE
Errors shown in Chrome console

### ISSUE THREAD

**Issue by mm108** [dreamfactorysoftware/openshift-dreamfactory-cartridge#5]
hi,

I have just used the Dreamfactory Cartridge for Openshift and created an application. Everything went through smoothly and I can access the application. But when I looked at the Chrome console, I saw a bunch of errors. Just wondering if any of the below needs to be fixed or should be of concern? Cos soon I will be moving this to production environment. I am logged in to an admin account

![dreamfactory_chrome_console_errors](https://cloud.githubusercontent.com/assets/10776430/13552106/672b2658-e38d-11e5-9c57-c259f6ac5ac3.jpg)

**Comment by todda48** [comment]
Those errors are related to the movies embedded on the Home page. The movies work. Nothing to worry about.
